### ISSUE TITLE
Text fields cleared while typing in Task Description field

### ISSUE THREAD

**Issue by ripper234** [Metaburn/doocrate#178]
If I continue typing in the 2nd field that current has מנהל המחנה, sometimes the entire form gets deleted. I have been able to reproduce this a few times, but not consistently.

![image](https://user-images.githubusercontent.com/172282/68332411-6d51b600-00df-11ea-8ce2-40b971a50fd4.png)

**Comment by ripper234** [comment]
Now I selected a Task Type from the combo box, and everything got cleared again.
Super frustrating.

**Comment by ripper234** [comment]
Guess: could it be just because someone else, at the same time, did _something_ with the system?

**Comment by rootux** [comment]
Fixed. There was some issue where an update to the list causes a refresh to your open tasks.
Didn't saw that one coming :) Anyway it's fixed now. Hopefully no more frustrations.
