### ISSUE TITLE
Make the grid more responsive

### ISSUE THREAD

**Issue by NirBenita** [Metaburn/doocrate#180]
As it stands now, the grid items have a fixed width no matter how much margins are created on the side. I would like to have the grid items expand to fill as much space as they have.

**Comment by rootux** [comment]
Looks like this is done - closing it 
<img width="1440" alt="Screen Shot 2020-08-12 at 16 16 04" src="https://user-images.githubusercontent.com/1032526/90019475-21a7ea80-dcb7-11ea-8caf-4128a396b121.png">

**Comment by NirBenita** [comment]
> Looks like this is done - closing it

Forgot to attach the PR, that's why it remained open
