### ISSUE TITLE
Click on a label to filter by it

### ISSUE THREAD

**Issue by ripper234** [Metaburn/doocrate#55]
Clicking on a label should add the label to the current filter.

When I click here:

![image](https://user-images.githubusercontent.com/172282/32191164-c86cae76-bdb8-11e7-856e-3c3467e4f4e3.png)

or here

![image](https://user-images.githubusercontent.com/172282/32191180-db63f78c-bdb8-11e7-87b8-3ea22a22d0a6.png)

I should get to this page

![image](https://user-images.githubusercontent.com/172282/32191213-f8ac97ae-bdb8-11e7-900c-77160251ddd0.png)

**Comment by rootux** [comment]
@ripper234  Done. Clicking on a label now filters by it 
<img width="1298" alt="Screen Shot 2019-11-01 at 22 42 03" src="https://user-images.githubusercontent.com/1032526/68065540-e4aad280-fcf8-11e9-8027-b8667f71ad26.png">

**Comment by ripper234** [comment]
Yay! 🍾
